# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: darmendarizp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: example
# "service" is the name of this project. This will also be added to your AWS resource names.
service: src

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  region: us-east-2
  iam:
    role:
      statements:
        # Permission for Bedrock model invocation
        - Effect: "Allow"
          Action:
            - "bedrock:InvokeModel"
          Resource:
            # Use the correct ARN format for Bedrock models
            - "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0"

# Add package configuration to exclude files and directories
package:
  patterns:
    - "!.venv/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.env"
    - "!.git/**"
    - "!.idea/**"
    - "!.vscode/**"
    - "!*.pyc"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
